version: '3'
services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      NODE_ENV: production
    command: yarn start:dev

volumes:
  postgres_data: